import React from "react";
import ReactDOM from "react-dom/client";

const Start = () => {
  return (
    <div class="start">
      <label for="weeks">Select a week: </label>
      <select name="weeks" id="weeks">
        <option value="1">Week 1</option>
        <option value="2">Week 2</option>
        <option value="3">Week 3</option>
        <option value="4">Week 4</option>
        <option value="5">Week 5</option>
        <option value="6">Week 6</option>
        <option value="7">Week 7</option>
        <option value="8">Week 8</option>
        <option value="9">Week 9</option>
        <option value="10">Week 10</option>
        <option value="11">Week 11</option>
        <option value="12">Week 12</option>
        <option value="13">Week 13</option>
        <option value="14">Week 14</option>
        <option value="15">Week 15</option>
        <option value="16">Week 16</option>
        <option value="17">Week 17</option>
        <option value="18">Week 18</option>
        <option value="19">Week 19</option>
        <option value="20">Week 20</option>
        <option value="21">Week 21</option>
        <option value="22">Week 22</option>
        <option value="23">Week 23</option>
        <option value="24">Week 24</option>
      </select>

      <p>Input NBA power rankings for week:</p>
      {/*********************************************************************/}
      {/* TODO: Make 30 input text boxes that auto-suggest each team instead*/}
      <label for="team_1">Team #1: </label>
      <select name="team_1" id="team_1">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_2">Team #2: </label>
      <select name="team_2" id="team_2">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_3">Team #3: </label>
      <select name="team_3" id="team_3">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_4">Team #4: </label>
      <select name="team_4" id="team_4">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_5">Team #5: </label>
      <select name="team_5" id="team_5">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_6">Team #6: </label>
      <select name="team_6" id="team_6">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_7">Team #7: </label>
      <select name="team_7" id="team_7">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_8">Team #8: </label>
      <select name="team_8" id="team_8">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_9">Team #9: </label>
      <select name="team_9" id="team_9">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_10">Team #10: </label>
      <select name="team_10" id="team_10">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_11">Team #11: </label>
      <select name="team_11" id="team_11">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_12">Team #12: </label>
      <select name="team_12" id="team_12">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_13">Team #13: </label>
      <select name="team_13" id="team_13">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_14">Team #14: </label>
      <select name="team_14" id="team_14">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_15">Team #15: </label>
      <select name="team_15" id="team_15">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_16">Team #16: </label>
      <select name="team_16" id="team_16">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_17">Team #17: </label>
      <select name="team_17" id="team_17">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_18">Team #18: </label>
      <select name="team_18" id="team_18">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_19">Team #19: </label>
      <select name="team_19" id="team_19">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_20">Team #20: </label>
      <select name="team_20" id="team_20">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_21">Team #21: </label>
      <select name="team_21" id="team_21">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_22">Team #22: </label>
      <select name="team_22" id="team_22">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_23">Team #23: </label>
      <select name="team_23" id="team_23">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>
      <label for="team_24">Team #24: </label>
      <select name="team_24" id="team_24">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_25">Team #25: </label>
      <select name="team_25" id="team_25">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_26">Team #26: </label>
      <select name="team_26" id="team_26">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_27">Team #27: </label>
      <select name="team_27" id="team_27">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_28">Team #28: </label>
      <select name="team_28" id="team_28">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>

      <label for="team_29">Team #29: </label>
      <select name="team_29" id="team_29">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>
      <label for="team_30">Team #30: </label>
      <select name="team_30" id="team_30">
        <option value="Atlanta Hawks">Atlanta Hawks</option>
        <option value="Boston Celtics">Boston Celtics</option>
        <option value="Brooklyn Nets">Brooklyn Nets</option>
        <option value="Charlotte Hornets">Charlotte Hornets</option>
        <option value="Chicago Bulls">Chicago Bulls</option>
        <option value="Cleveland Caveliers">Cleveland Caveliers</option>
        <option value="Dallas Mavericks">Dallas Mavericks</option>
        <option value="Denver Nuggets">Denver Nuggets</option>
        <option value="Detroit Pistons">Detroit Pistons</option>
        <option value="Golden State Warriors">Golden State Warriors</option>
        <option value="Houston Rockets">Houston Rockets</option>
        <option value="Indiana Pacers">Indiana Pacers</option>
        <option value="Los Angeles Clippers">Los Angeles Clippers</option>
        <option value="Los Angeles Lakers">Los Angeles Lakers</option>
        <option value="Memphis Grizzlies">Memphis Grizzlies</option>
        <option value="Miami Heat">Miami Heat</option>
        <option value="Milwakee Bucks">Milwakee Bucks</option>
        <option value="Minnesota Timberwolves">Minnesota Timberwolves</option>
        <option value="New Orleans Pelicans">New Orleans Pelicans</option>
        <option value="New York Knicks">New York Knicks</option>
        <option value="Oklahoma City Thunder">Oklahoma City Thunder</option>
        <option value="Orlando Magic">Orlando Magic</option>
        <option value="Philadephia 76ers">Philadephia 76ers</option>
        <option value="Phoenix Suns">Phoenix Suns</option>
        <option value="Portland Trail Blazers">Portland Trail Blazers</option>
        <option value="Sacramento Kings">Sacramento Kings</option>
        <option value="San Antonio Spurs">San Antonio Spurs</option>
        <option value="Toronto Raptors">Toronto Raptors</option>
        <option value="Utah Jazz">Utah Jazz</option>
        <option value="Washington Wizards">Washington Wizards</option>
      </select>
    </div>
  );
};

export default Start;
